channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==6.0.0
  - scikit-learn==1.6.1
  - scipy==1.14.1
name: mlflow-env
